language: python

python:
  - "2.7"

install:
  - cd update-bot
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - cp user-config.template.py user-config.py
  - cp local_family.template.py local_family.py

script:
  - python -m unittest discover .

